name: Gradle check

on: [push]

jobs:
  gradle-build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build with Gradle
      run: |
        ./gradlew check
