name: Gradle check

on: [push]

jobs:
  gradle-build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up JDK 8
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        java-version: 8
        distribution: 'temurin'

    - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
      with:
        cache-read-only: false

    - name: Build with Gradle
      run: |
        ./gradlew check --full-stacktrace

    - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      if: always()
      with:
        name: reports
        path: build/reports
