on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0.1
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

name: Release Gradle plugin

jobs:
  build:
    name: Publish Gradle plugin release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        with:
          cache-read-only: false

      - name: Load jreleaser config
        run: |
          mkdir -p "$HOME/.jreleaser"
          echo "${{ secrets.JRELEASER_CONFIG_B64 }}" | base64 -d > "$HOME/.jreleaser/config.toml"
          chmod 600 "$HOME/.jreleaser/config.toml"

      - name: Build
        run: ./gradlew :build --full-stacktrace

      - name: Stage maven central deploy
        run: ./gradlew :publishMavenCentralPublicationToStagingDeployRepository --full-stacktrace

      - name: Publish to Maven Central
        run: ./gradlew :jreleaserFullRelease --full-stacktrace

#      - name: Publish to Gradle Plugin Portal
#        run: ./gradlew :publishPlugin -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} --full-stacktrace
